# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdc26fa0599f3f79ff069738bf13ca4a38cc1b15787910a5e342fe093fb3f799240e3d41aea89548bde78efc58f0bd46a9d34d8dc3bb13c1e033c0f21312a92d

test:
  secret_key_base: b54bd1394a736fe006abb1e89bee0052b6b45bb18c16977c9bc1b767686987ecc807656c283fae7f2c1ad08a7bea58b3819945d229555d41194ff51ab1ac8f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
